### ISSUE TITLE
Aging chart throws Error "object 'Type' not found"

### ISSUE THREAD

**Issue by jeepcreep** [gabriprat/lean-tracking#3]
though I'm not that much into R I was able to fix it via changing

`p <- ggplot(data, aes(x = lastState, y = Age)) + 
        geom_jitter(aes(text=ID, colour=Type), alpha = 0.3, width=.5, height=0) `

to

`p <- ggplot(data, aes(x = lastState, y = Age)) + 
        geom_jitter(aes_string(text="ID", colour = input$columnType), alpha = 0.3, width=.5, height=0) `

**Comment by atassani** [comment]
Thanks for your interest. Your proposal has been added to the code.
